# Pre-requisites:
# 1. Install LM-Proxy:
# > pip install lm-proxy
# 2. Install Vertex AI API: 
# > pip install vertexai
# 3. Install Google Cloud SDK: https://cloud.google.com/sdk/docs/install
# 4. Authenticate with Google Cloud: `gcloud auth application-default login`
# 5. Set your Google Cloud project: `gcloud config set project <PROJECT_ID>`
# 6. Save this config to a file named `vertex-ai.toml`
# 7. Fill connections.vertex_ai.google_vertex_project_id
# 8. Run LM-Proxy with this config:
# > lm-proxy --config vertex-ai.toml
[connections]
[connections.vertex_ai]
api_type = "google_vertex_ai"
google_vertex_project_id = "<PROJECT_ID>"
google_vertex_gcloud_auth  = true
google_vertex_response_validation = true
model = "gemini-2.5-pro"

[routing]
"gemini-2.5-pro" = "vertex_ai.gemini-2.5-pro"

[groups.default]
api_keys = [
    "KEY1",
    "KEY2"
]
