name: Tests and Coverage Badge

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  test-internal:
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
    uses: ./.github/workflows/tests.reusable.yml
    with:
      ref: ${{ github.ref }}
      update-badge: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    secrets: inherit

  test-external:
    if: |
      github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository
    uses: ./.github/workflows/tests.reusable.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      # Environment requiring mandatory code check by maintainers
      # to mitigate exfiltrating secrets using malicious code in PRs.
      environment: external-pr
    secrets: inherit  # Required for passing secrets to reusable workflow.
